name: build_package_rpi

on:
  push:
   branches:
      - "*"
   tags:
      - "*"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [bullseye, bookworm]
        include:
        - target: bullseye
          base_image: raspios_lite:2023-05-03
        - target: bookworm
          base_image: raspios_lite:latest
    steps:    
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@98b8d5a3228f504a8bd54913ab1e23d70f369c6e
      id: build_image
      with:
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: "**/*.deb"
        import_github_env: true
        commands: |
            cd /opt
            cd OpenHD
            mkdir -p /usr/local/share/openhd/
            touch /usr/local/share/openhd/joyconfig.txt
            sudo ./install_build_dep.sh rpi
            cd /opt
            cd OpenHD
            chown -R root:root ../OpenHD
            sudo ./package.sh standard armhf raspbian ${{ matrix.target }}
            #ls -falnR
            #mv *.deb ./OpenHD/

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "OpenHD-${{ matrix.target }}"
        path: |
          "*-${{ matrix.target }}.deb"
        if-no-files-found: error
